/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sites */
        get: operations["get_sites_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Runs
         * @description The forecast runs that can be served, newest first -- what a run picker
         *     offers. Any of them is a valid `run_ts` for the operational endpoints.
         */
        get: operations["get_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Forecast */
        get: operations["get_forecast_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/outlook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Outlook */
        get: operations["get_outlook_outlook_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Actions */
        get: operations["get_actions_actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{action_id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge Action */
        post: operations["acknowledge_action_actions__action_id__ack_post"];
        /** Withdraw Acknowledgement */
        delete: operations["withdraw_acknowledgement_actions__action_id__ack_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/storage/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Storage Sweep */
        get: operations["get_storage_sweep_storage_sweep_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Backtest
         * @description Accuracy per lead hour, from the walk-forward backtest, plus its headline.
         *
         *     No time-window parameters, deliberately, though dev-01 4 lists them: this
         *     table is aggregated ACROSS the whole walk-forward and indexed by lead hour,
         *     so it carries no `valid_ts_utc` to slice on. Accepting a window would have
         *     quietly returned an empty frame for every caller that passed one.
         */
        get: operations["get_backtest_backtest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Explain
         * @description Why is this forecast where it is? -- ranked drivers of the correction.
         *
         *     Reads what `run_cycle.py` precomputed; the API never runs SHAP itself.
         */
        get: operations["get_explain_explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckResponse */
        AckResponse: {
            /** Region Id */
            region_id: string;
            /** Action Id */
            action_id: string;
            /** Acknowledged At */
            acknowledged_at?: string | null;
        };
        /**
         * Action
         * @enum {string}
         */
        Action: "HOLD" | "CURTAIL" | "CHARGE_BESS" | "DISCHARGE_BESS" | "COMMIT_BACKUP";
        /** ActionsResponse */
        ActionsResponse: {
            /** Region Id */
            region_id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Model Version
             * @default unavailable
             */
            model_version: string;
            /** Calibration Date */
            calibration_date?: string | null;
            /**
             * Nwp Models
             * @default []
             */
            nwp_models: string[];
            /**
             * Replay Mode
             * @default false
             */
            replay_mode: boolean;
            /** Age Minutes */
            age_minutes?: number | null;
            /** Data */
            data: components["schemas"]["Recommendation"][];
        };
        /** BacktestResponse */
        BacktestResponse: {
            /** Region Id */
            region_id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Model Version
             * @default unavailable
             */
            model_version: string;
            /** Calibration Date */
            calibration_date?: string | null;
            /**
             * Nwp Models
             * @default []
             */
            nwp_models: string[];
            /**
             * Replay Mode
             * @default false
             */
            replay_mode: boolean;
            /** Age Minutes */
            age_minutes?: number | null;
            /** Data */
            data: components["schemas"]["LeadHourMetric"][];
            summary?: components["schemas"]["BacktestSummary"] | null;
        };
        /**
         * BacktestSummary
         * @description The headline over the whole walk-forward.
         *
         *     Computed by `evaluation.report.summarise` -- the same function that writes
         *     `artifacts/backtest.json` -- so the served headline and the published one
         *     cannot disagree. Clients must not re-derive it from the per-lead rows: the
         *     obvious pooled RMS gives 6.05% solar nRMSE where the headline (a row-weighted
         *     mean, skill from the aggregated errors) is 5.36%.
         */
        BacktestSummary: {
            /** Folds */
            folds?: number | null;
            /** N Rows */
            n_rows: number;
            /** Leads Scored */
            leads_scored: number;
            /** Leads In Band */
            leads_in_band: number;
            /** Picp Target Low */
            picp_target_low: number;
            /** Picp Target High */
            picp_target_high: number;
            /** Nrmse Mean */
            nrmse_mean?: number | null;
            /** Nrmse Persistence */
            nrmse_persistence?: number | null;
            /** Nrmse Physics */
            nrmse_physics?: number | null;
            /** Nrmse Tso */
            nrmse_tso?: number | null;
            /** Nrmse Tso Wa */
            nrmse_tso_wa?: number | null;
            /** Skill Mean */
            skill_mean?: number | null;
            /** Skill Vs Physics */
            skill_vs_physics?: number | null;
            /** Mbe Mean */
            mbe_mean?: number | null;
            /** Picp Mean */
            picp_mean?: number | null;
        };
        /**
         * Driver
         * @description One feature's signed contribution to the p50 residual correction.
         *
         *     Units are capacity factor, and the sign is meaningful: positive means this
         *     feature pushed the forecast ABOVE what physics alone predicted.
         */
        Driver: {
            /**
             * Valid Ts Utc
             * Format: date-time
             */
            valid_ts_utc: string;
            /** Lead Hours */
            lead_hours: number;
            tech: components["schemas"]["Tech"];
            /** Rank */
            rank: number;
            /** Feature */
            feature: string;
            /** Value */
            value?: number | null;
            /** Contribution */
            contribution: number;
            /** Base Cf */
            base_cf?: number | null;
            /** Prediction Cf */
            prediction_cf?: number | null;
        };
        /** EventsResponse */
        EventsResponse: {
            /** Region Id */
            region_id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Model Version
             * @default unavailable
             */
            model_version: string;
            /** Calibration Date */
            calibration_date?: string | null;
            /**
             * Nwp Models
             * @default []
             */
            nwp_models: string[];
            /**
             * Replay Mode
             * @default false
             */
            replay_mode: boolean;
            /** Age Minutes */
            age_minutes?: number | null;
            /** Data */
            data: components["schemas"]["GridEvent"][];
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Region Id */
            region_id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Model Version
             * @default unavailable
             */
            model_version: string;
            /** Calibration Date */
            calibration_date?: string | null;
            /**
             * Nwp Models
             * @default []
             */
            nwp_models: string[];
            /**
             * Replay Mode
             * @default false
             */
            replay_mode: boolean;
            /** Age Minutes */
            age_minutes?: number | null;
            /** Data */
            data: components["schemas"]["Driver"][];
        };
        /**
         * Flag
         * @enum {string}
         */
        Flag: "NORMAL" | "OVER_GENERATION" | "STEEP_RAMP" | "DEFICIT_RISK" | "STORM_SHUTDOWN" | "LOW_CONFIDENCE";
        /** ForecastPoint */
        ForecastPoint: {
            /**
             * Valid Ts Utc
             * Format: date-time
             */
            valid_ts_utc: string;
            /** Lead Hours */
            lead_hours: number;
            tech: components["schemas"]["Tech"];
            /** P10 Mw */
            p10_mw: number;
            /** P50 Mw */
            p50_mw: number;
            /** P90 Mw */
            p90_mw: number;
            /** Capacity Mw */
            capacity_mw: number;
            /**
             * Calibrated
             * @default false
             */
            calibrated: boolean;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Region Id */
            region_id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Model Version
             * @default unavailable
             */
            model_version: string;
            /** Calibration Date */
            calibration_date?: string | null;
            /**
             * Nwp Models
             * @default []
             */
            nwp_models: string[];
            /**
             * Replay Mode
             * @default false
             */
            replay_mode: boolean;
            /** Age Minutes */
            age_minutes?: number | null;
            /** Data */
            data: components["schemas"]["ForecastPoint"][];
        };
        /** GridEvent */
        GridEvent: {
            /** Event Id */
            event_id: string;
            flag: components["schemas"]["Flag"];
            /** Severity */
            severity: number;
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
            /** Lead Hours */
            lead_hours: number;
            /** Magnitude Mw */
            magnitude_mw: number;
            /** Energy Mwh */
            energy_mwh: number;
            /** Description */
            description: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
            /** Replay Mode */
            replay_mode: boolean;
            /** Regions */
            regions: string[];
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * LeadHourMetric
         * @description One lead hour of the walk-forward backtest.
         *
         *     The evaluation track owns the gold table and its metric set may grow, so
         *     `extra="allow"` lets a new column through rather than 500ing the endpoint
         *     the day it lands. The named fields are the ones a client can rely on --
         *     everything here is NORMALISED by installed capacity, which is why there is
         *     no `_mw` metric in the list: megawatt errors are not comparable between two
         *     regions, two technologies, or the same fleet a year apart.
         */
        LeadHourMetric: {
            /** Lead Hours */
            lead_hours: number;
            tech: components["schemas"]["Tech"];
            /** N Rows */
            n_rows?: number | null;
            /** Nrmse Model */
            nrmse_model?: number | null;
            /** Nrmse Persistence */
            nrmse_persistence?: number | null;
            /** Nrmse Physics */
            nrmse_physics?: number | null;
            /** Nrmse Tso */
            nrmse_tso?: number | null;
            /** Skill Vs Persistence */
            skill_vs_persistence?: number | null;
            /** Picp 80 */
            picp_80?: number | null;
            /** Mean Width Frac */
            mean_width_frac?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** OutlookPoint */
        OutlookPoint: {
            /**
             * Valid Ts Utc
             * Format: date-time
             */
            valid_ts_utc: string;
            /** Lead Hours */
            lead_hours: number;
            /** Demand Mw */
            demand_mw: number;
            /** Solar P10 Mw */
            solar_p10_mw: number;
            /** Solar P50 Mw */
            solar_p50_mw: number;
            /** Solar P90 Mw */
            solar_p90_mw: number;
            /** Wind P10 Mw */
            wind_p10_mw: number;
            /** Wind P50 Mw */
            wind_p50_mw: number;
            /** Wind P90 Mw */
            wind_p90_mw: number;
            /** Net Load Mw */
            net_load_mw: number;
            /** Net Load P10 Mw */
            net_load_p10_mw: number;
            /** Net Load P90 Mw */
            net_load_p90_mw: number;
            /** Must Run Mw */
            must_run_mw: number;
            /** Headroom Mw */
            headroom_mw: number;
            /** Ramp Mw Per H */
            ramp_mw_per_h?: number | null;
        };
        /** OutlookResponse */
        OutlookResponse: {
            /** Region Id */
            region_id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Model Version
             * @default unavailable
             */
            model_version: string;
            /** Calibration Date */
            calibration_date?: string | null;
            /**
             * Nwp Models
             * @default []
             */
            nwp_models: string[];
            /**
             * Replay Mode
             * @default false
             */
            replay_mode: boolean;
            /** Age Minutes */
            age_minutes?: number | null;
            /** Data */
            data: components["schemas"]["OutlookPoint"][];
        };
        /** Recommendation */
        Recommendation: {
            /** Action Id */
            action_id: string;
            action: components["schemas"]["Action"];
            flag: components["schemas"]["Flag"];
            /**
             * Valid From
             * Format: date-time
             */
            valid_from: string;
            /**
             * Valid To
             * Format: date-time
             */
            valid_to: string;
            /** Power Mw */
            power_mw: number;
            /** Mwh */
            mwh: number;
            /** Value Inr */
            value_inr: number;
            /** Confidence */
            confidence: number;
            /** Decisive */
            decisive: boolean;
            /** Rationale */
            rationale: string;
            /** Linked Event Id */
            linked_event_id?: string | null;
            /** Acknowledged At */
            acknowledged_at?: string | null;
        };
        /** RunsResponse */
        RunsResponse: {
            /** Region Id */
            region_id: string;
            /** Replay Mode */
            replay_mode: boolean;
            /** Latest */
            latest?: string | null;
            /** Runs */
            runs: string[];
        };
        /** SiteInfo */
        SiteInfo: {
            /** Region Id */
            region_id: string;
            /** Timezone */
            timezone: string;
            /** Capacity Mw */
            capacity_mw: {
                [key: string]: number;
            };
            /** Nwp Models */
            nwp_models: string[];
            /**
             * Physics Only
             * @default false
             */
            physics_only: boolean;
        };
        /** SweepPoint */
        SweepPoint: {
            /** Energy Capacity Mwh */
            energy_capacity_mwh: number;
            /** Curtailment Avoided Gwh Yr */
            curtailment_avoided_gwh_yr: number;
            /** Value Inr Yr */
            value_inr_yr: number;
            /** Cycles Per Year */
            cycles_per_year: number;
        };
        /** SweepResponse */
        SweepResponse: {
            /** Region Id */
            region_id: string;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /**
             * Model Version
             * @default unavailable
             */
            model_version: string;
            /** Calibration Date */
            calibration_date?: string | null;
            /**
             * Nwp Models
             * @default []
             */
            nwp_models: string[];
            /**
             * Replay Mode
             * @default false
             */
            replay_mode: boolean;
            /** Age Minutes */
            age_minutes?: number | null;
            /** Data */
            data: components["schemas"]["SweepPoint"][];
        };
        /**
         * Tech
         * @enum {string}
         */
        Tech: "solar" | "wind";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_sites_sites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteInfo"][];
                };
            };
        };
    };
    get_runs_runs_get: {
        parameters: {
            query: {
                region_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_forecast_forecast_get: {
        parameters: {
            query: {
                region_id: string;
                run_ts?: string | null;
                horizon_hours?: number;
                tech?: components["schemas"]["Tech"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_outlook_outlook_get: {
        parameters: {
            query: {
                region_id: string;
                run_ts?: string | null;
                horizon_hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutlookResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_events_get: {
        parameters: {
            query: {
                region_id: string;
                run_ts?: string | null;
                min_severity?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_actions_actions_get: {
        parameters: {
            query: {
                region_id: string;
                run_ts?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_action_actions__action_id__ack_post: {
        parameters: {
            query: {
                region_id: string;
                run_ts?: string | null;
            };
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_acknowledgement_actions__action_id__ack_delete: {
        parameters: {
            query: {
                region_id: string;
                run_ts?: string | null;
            };
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_storage_sweep_storage_sweep_get: {
        parameters: {
            query: {
                region_id: string;
                max_mwh?: number;
                steps?: number;
                run_ts?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SweepResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_backtest_get: {
        parameters: {
            query: {
                region_id: string;
                tech: components["schemas"]["Tech"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_explain_explain_get: {
        parameters: {
            query: {
                region_id: string;
                tech?: components["schemas"]["Tech"] | null;
                valid_ts?: string | null;
                run_ts?: string | null;
                top_n?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
